name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: ./scripts/build.ps1
        shell: pwsh

      - name: Test
        run: ./scripts/test.ps1
        shell: pwsh

      - name: Pack
        run: ./scripts/pack.ps1
        shell: pwsh
